package chain

import (
	"flag"
	"os"
	"path/filepath"
	"testing"
)

// update rewrites the frozen golden testdata files. The standard Go
// golden-file idiom. The goldens are FIRST generated by running with
// -update, then committed; thereafter -update is for INTENTIONAL wire-
// format bumps only. Misuse silently rewrites the contract, so cases
// 3/4/5 (verify + import-stability + genesis-hash) still fail loudly
// if a regenerated golden is internally inconsistent.
//
// regen: go test ./pkg/chain -run TestGoldenChainV1 -update
var update = flag.Bool("update", false, "rewrite golden testdata")

// TestGoldenChainV1_PrettyExportMatchesFrozen pins the pretty
// (MarshalIndent) Export bytes of the golden 3-receipt chain.
func TestGoldenChainV1_PrettyExportMatchesFrozen(t *testing.T) {
	c := BuildGoldenChainV1()
	got, err := c.Export()
	if err != nil {
		t.Fatalf("Export: %v", err)
	}
	goldenPath := filepath.Join("testdata", "golden_chain_v1.json")
	if *update {
		if err := os.WriteFile(goldenPath, got, 0o644); err != nil {
			t.Fatalf("update golden: %v", err)
		}
	}
	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden (run -update to create): %v", err)
	}
	if string(got) != string(want) {
		t.Fatalf("golden_chain_v1.json byte drift:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestGoldenChainV1_CompactExportMatchesFrozen pins the compact
// (no-whitespace) Export bytes of the same chain.
func TestGoldenChainV1_CompactExportMatchesFrozen(t *testing.T) {
	c := BuildGoldenChainV1()
	got, err := c.ExportCompact()
	if err != nil {
		t.Fatalf("ExportCompact: %v", err)
	}
	goldenPath := filepath.Join("testdata", "golden_chain_v1.compact.json")
	if *update {
		if err := os.WriteFile(goldenPath, got, 0o644); err != nil {
			t.Fatalf("update golden: %v", err)
		}
	}
	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden (run -update to create): %v", err)
	}
	if string(got) != string(want) {
		t.Fatalf("golden_chain_v1.compact.json byte drift:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestGoldenChainV1_VerifiesUnderKAT1Substrate confirms the golden
// chain is itself valid: it must verify under the same KAT-1 Mirror-
// Mark substrate that signed it.
func TestGoldenChainV1_VerifiesUnderKAT1Substrate(t *testing.T) {
	c := BuildGoldenChainV1()
	v := MirrorMarkVerifier(KAT1CorpusSHA(), KAT1CanonicalKey())
	if err := c.Verify(v); err != nil {
		t.Fatalf("golden chain failed Verify under KAT-1 substrate: %v", err)
	}
}

// TestGoldenChainV1_ImportReExportIsStable re-imports the frozen pretty
// bytes and asserts the resulting chain re-exports byte-identically —
// the round-trip + golden pin in one assertion (catches Import/Export
// asymmetry).
func TestGoldenChainV1_ImportReExportIsStable(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("testdata", "golden_chain_v1.json"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	c, err := Import(raw)
	if err != nil {
		t.Fatalf("Import: %v", err)
	}
	re, err := c.Export()
	if err != nil {
		t.Fatalf("re-Export: %v", err)
	}
	if string(re) != string(raw) {
		t.Fatalf("Import->Export not byte-stable:\n--- re-export ---\n%s\n--- frozen ---\n%s", re, raw)
	}
}

// TestGoldenChainV1_GenesisReceiptHashPinned inline-pins the genesis
// receipt hash so a cross-substrate port can check ONE value without
// parsing JSON (the cheapest cross-substrate smoke check).
func TestGoldenChainV1_GenesisReceiptHashPinned(t *testing.T) {
	c := BuildGoldenChainV1()
	g, ok := c.Genesis()
	if !ok {
		t.Fatalf("golden chain has no genesis receipt")
	}
	const want = "a91ccd9b32aa992e7d8f52c469a4d80888428e024acb5bf5af03bcee5cd303b5"
	if got := g.Hash(); got != want {
		t.Fatalf("genesis receipt hash drift: got %s want %s", got, want)
	}
}
